# Generated by Django 3.1.7 on 2021-03-11 01:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210310_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
