# Generated by Django 3.1.7 on 2021-03-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210310_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='img',
        ),
    ]
