# Generated by Django 3.1.7 on 2021-03-11 02:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_food_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
